Test/usage text
Scottish-Natural-Heritage/trap-registration-return pull request #13
Opened 2021-01-28 12:12 UTC by murrayholmes96

Sorry about bad branch name pushed this as a test but seemingly works

Scottish-Natural-Heritage/Licensing#478

2021-01-28 14:54 UTC, MikeCoats requested changes
A couple of wee questions and something I think is a copy/paste error.

2021-01-28 14:54 UTC, MikeCoats commented on cypress/integration/003-usage.js
> -
Not sure why this line needed to be removed...

2021-01-28 14:54 UTC, MikeCoats commented on cypress/integration/003-usage.js
> -
...or these ones. I'm pretty sure they were there to visually distinguish separate tests. Did this get flagged by the linter?

2021-01-28 14:54 UTC, MikeCoats commented on src/views/usage.njk
> +-{% from "govuk/components/error-summary/macro.njk" import govukErrorSummary %}
Not sure about those `-` at the start of every line. Pretty sure they're an accidental addition.

2021-01-29 10:07 UTC, murrayholmes96 commented
The errors are from copy and pasting, hopefully fixed now

2021-01-29 10:41 UTC, MikeCoats commented on cypress/integration/003-usage.js
> -
Resolved in 911481548a8e2d58a41903741679c291d257b844.

2021-01-29 10:41 UTC, MikeCoats commented on cypress/integration/003-usage.js
> -
Resolved in 911481548a8e2d58a41903741679c291d257b844.

2021-01-29 10:41 UTC, MikeCoats commented on src/views/usage.njk
> +-{% from "govuk/components/error-summary/macro.njk" import govukErrorSummary %}
Resolved in 911481548a8e2d58a41903741679c291d257b844.

2021-01-29 13:03 UTC, MikeCoats approved these changes

2021-01-29 13:03 UTC, merged