Added text to Start page as requested by Katherine
Scottish-Natural-Heritage/trap-registration-return pull request #7
Opened 2020-12-22 12:00 UTC by murrayholmes96

Added text to start page

2020-12-22 12:10 UTC, murrayholmes96 commented
#484

2020-12-22 12:35 UTC, paulcoxsnh commented on src/views/start.njk
> +      If you need any assistance with this registration, vontact the NatureScot Liscensing Team.
Should be `contact`?

2020-12-22 12:42 UTC, paulcoxsnh requested changes
Just one little typo, the rest all looks good :)

2021-01-13 08:03 UTC, paulcoxsnh commented on src/views/start.njk
> +      If you need any assistance with this registration, vontact the NatureScot Liscensing Team.
Resolved in https://github.com/Scottish-Natural-Heritage/trap-registration-return/pull/7/commits/f0334437e70fd46a2e2c5abc78b1c6645feab2b4

2021-01-13 08:04 UTC, paulcoxsnh approved these changes
All looks good :)

2021-01-13 08:04 UTC, merged